run:
  # Allow multiple parallel golangci-lint instances running.
  # If false (default) - golangci-lint acquires file lock on start.
  allow-parallel-runners: true

linters:
  # https://golangci-lint.run/usage/configuration/

linters-settings:
  gofmt:
    rewrite-rules:
      # ensure `any` is used instead of `interface{}` - https://tip.golang.org/doc/go1.18
      - pattern: 'interface{}'
        replacement: 'any'
